language: ruby
rvm:
  - 1.9.3
script:
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
notifications:
  campfire:
    rooms:
      secure: ZajSlUQKuUK6LnLIaPFEfITUS+w6UCAUqnaZnWQBq+976lR0ajhkxOx4Azr9DYTSC4EVpqV948xLTbnpBXCKhNGU70L1/C6cH71oreGW+u+9yCtGC8OskZtYUZrli6bDn2skIjNeFsO0Z7w4SC3uAHL6KnhPBiAKJGFYzNDCV8A=
    on_success: change
    on_failure: always
